# 02 — Exploratory Data Analysis
Compare demand magnitude, 24-hour profiles, weekday/weekend behavior, peak timing, and variability.

In [1]:
from pathlib import Path
import sys

project_root = Path.cwd().resolve()
if not (project_root / "src" / "data_preparation.py").is_file():
    project_root = project_root.parent
if not (project_root / "src" / "data_preparation.py").is_file():
    raise FileNotFoundError("Run this notebook from the project root or notebooks directory.")
if str(project_root) not in sys.path:
    sys.path.insert(0, str(project_root))

import pandas as pd
from src.eda import period_summary, hourly_profile, day_type_profile, daily_peaks, peak_hour_distribution

df = pd.read_csv(project_root / "data/processed/luzon_hourly_clean.csv", parse_dates=["date", "datetime"])
period_summary(df)

,period,observations,mean_mw,median_mw,std_mw,min_mw,max_mw
0,Pre-pandemic,26280,7858.469901,7866.5,1260.517308,4077.0,11301.0
1,Pandemic,17544,8055.740367,8067.0,1174.252575,2694.0,11599.0
2,Recovery,26304,9262.990270,9235.5,1407.561848,4879.0,13957.0

In [2]:
hourly_profile(df).head(30)

          period  hour    demand_mw
0       Pandemic     0  7469.383037
1       Pandemic     1  7222.586867
2       Pandemic     2  6997.653899
3       Pandemic     3  6829.218878
4       Pandemic     4  6775.794802
5       Pandemic     5  6761.965800
6       Pandemic     6  6930.946648
7       Pandemic     7  7535.184679
8       Pandemic     8  8149.570451
9       Pandemic     9  8614.471956
10      Pandemic    10  8922.679891
11      Pandemic    11  8801.064295
12      Pandemic    12  8836.351573
13      Pandemic    13  9083.770178
14      Pandemic    14  8993.445964
15      Pandemic    15  8781.474692
16      Pandemic    16  8379.242134
17      Pandemic    17  8362.153215
18      Pandemic    18  8581.660739
19      Pandemic    19  8546.145007
20      Pandemic    20  8543.987688
21      Pandemic    21  8373.751026
22      Pandemic    22  8079.073871
23      Pandemic    23  7766.191518
24  Pre-pandemic     0  6973.662100
25  Pre-pandemic     1  6747.053881
26  Pre-pandemic     2  6551.099543
27  Pre-pandemic     3  6430.337900
28  Pre-pandemic     4  6477.110502
29  Pre-pandemic     5  6497.082192

In [3]:
peak_hour_distribution(df).head(30)

          period  peak_hour  days     share
0       Pandemic          0     2  0.002736
1       Pandemic          8     1  0.001368
2       Pandemic          9     1  0.001368
3       Pandemic         10   125  0.170999
4       Pandemic         12     1  0.001368
5       Pandemic         13   406  0.555404
6       Pandemic         14    26  0.035568
7       Pandemic         15     1  0.001368
8       Pandemic         16     2  0.002736
9       Pandemic         17    23  0.031464
10      Pandemic         18    49  0.067031
11      Pandemic         19     7  0.009576
12      Pandemic         20    64  0.087551
13      Pandemic         21    23  0.031464
14  Pre-pandemic          0     2  0.001826
15  Pre-pandemic          2     1  0.000913
16  Pre-pandemic          9     2  0.001826
17  Pre-pandemic         10   240  0.219178
18  Pre-pandemic         13   622  0.568037
19  Pre-pandemic         14    14  0.012785
20  Pre-pandemic         15     2  0.001826
21  Pre-pandemic         17    21  0.019178
22  Pre-pandemic         18    86  0.078539
23  Pre-pandemic         19    66  0.060274
24  Pre-pandemic         20    35  0.031963
25  Pre-pandemic         21     4  0.003653
26      Recovery          0     2  0.001825
27      Recovery          9     1  0.000912
28      Recovery         10   127  0.115876
29      Recovery         12     2  0.001825